### PR TITLE
Add state_class for statistics

### PR DESCRIPTION
**Pull request by phidauex**
This pull adds `state_class` to the sensor configuration, allowing the generated sensors to be used in the Home Assistant statistics module. It also resolves a minor bug where the Home Assistant autodiscovery module would choke on receiving a 'null' value for `unit_of_measurement`. This sends an empty string instead where the field isn't applicable, clearing the error.

### CODE REVIEW

**Comment by phidauex** [comment]
Oops, HA doesn't like having "" as a state_class. Pulling back until I resolve.

**Comment by IamTheCarl** [comment]
Sounds good. Nice to see you again.

**Comment by phidauex** [comment]
Thanks, I still love this little tool, and wanted to make some improvements to allow for statistics on the sensors. The good news is that these commits work, the bad news is that they throw HA log errors. Initially, I found that the validator did not like that `unit_of_measurement` could have a value of `null`. However, it doesn't mind having a value of `""` as an empty string, which it correctly interprets as `None` and doesn't use the key. Simple fix.

The problem is `state_class` which should work the same way. It accepts a value of `measurement`, `total`, or `total_increasing`. It *should* accept `""` or `None` as values as well, and not use the key. However, while HA seems to work fine using an empty key value, the validator script throws an invalid dict entry error. My suspicion right now is that it is the validator that is wrong, not the input, but I'll hold off until I have a better idea of the problem.

Error, for reference. Notable part is at the bottom.

```
xception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'name': 'helios64-battery_state', 
'state_class': 'None', 'state_topic': 'system-mqtt/helios64/battery_state', 'unit_of_measurement': '', 'icon': 'mdi:battery', 
'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components
/mqtt/mixins.py", line 315, in async_discover config = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10
/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) 
File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else 
AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v 
= func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return 
self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in 
validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272,
 in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line
 595, in validate_dict return base_validate(path, iteritems(data), out) File 
"/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise 
er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: expected SensorStateClass or one of 'measurement', 'total', 
'total_increasing' for dictionary value @ data['state_class'] 
```

**Comment by IamTheCarl** [comment]
I'm happy to see you like it. I still use it a lot myself.
I've been considering new features. I should probably spin up a new issue for those.

Is this validator script an official part of HA? I'm actually pretty unfamiliar with the HA codebase itself, although with some ideas I want to do with this project, I should get more familiar with it.

**Comment by phidauex** [comment]
Thanks! I'm going to go ahead and reopen the pull for the moment... After testing, the validator error shows up in the HA logs (yes, the validator is part of the HA stack), but the new tags do work. It isn't clear to me after investigation if the mqtt autodiscovery dict is wrong, or if the validator is wrong...

But at least the statistics view is very handy for long term things like CPU, like the below graph of max CPU per hour on each of my two servers:

image

**Comment by IamTheCarl** [comment]
It seems to be working well enough.
I'll merge it but can you give the version number in Cargo.toml a bump to `0.3.0`? This will make apt more friendly toward updates.

**Comment by IamTheCarl** [comment]
Also while I have your attention, could yo give me your opinion on issue https://github.com/IamTheCarl/system-mqtt/issues/4 ?

**Comment by IamTheCarl** [comment]
I am going to merge this now anyway, because I have started some fairly large changes and want to get these merged in before I make that too hard to do.

**Pull request merged**
